services:
  postgres:
    container_name: postgres-sql-legosn
    image: postgres
    environment:
      POSTGRES_USER: legosn
      POSTGRES_PASSWORD: legosn
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: lego_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-legosn-network
    restart: unless-stopped
  mail-dev:
    container_name: maildev-legosn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-legosn-network:
    driver: bridge

volumes:
  postgres:
    driver: local
